on:
  push:
  schedule:
    - cron: '40 8 * * *'

jobs:
  validate_job:
    name: Validation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Validate artists
        run: node ./validate/validate-artists.js
      - name: Validate titles
        run: node ./validate/validate-titles.js
      - name: Validate tracks metadata against Spotify
        run: node ./validate/validate-metadata.js
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
